import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowRight, ArrowUpRight, Menu, X, Instagram, Leaf, Heart, Sparkles, Droplets } from 'lucide-react';
import './styles.css';

const wa = 'https://wa.me/2348138920143';
const ig = 'https://www.instagram.com/bloomance1/';
const tt = 'https://www.tiktok.com/@bloomance1';

const products = [
  { name: 'Botanical Hair Oil', price: '₦5,000', type: 'Scalp & strand care', image: '/images/hair-oil.jpeg', number: '01', note: 'Nourish · Strengthen · Promote growth', text: 'A nourishing botanical blend created to care for the scalp and hair. Made with time-honoured herbs and lightweight oils for a comforting step in your regular hair-care routine.', ingredients: 'Amla, bhringraj, brahmi, ashwagandha, hibiscus, black seed, jojoba, sweet almond, coconut and sunflower oils, rosemary and lavender essential oils.', how: 'Apply a small amount to the scalp and massage gently with your fingertips. Smooth lightly through lengths and ends as needed.' },
  { name: 'Gentle Aloe Vera Shampoo', price: '₦4,500', type: 'Cleanse & hydrate', image: '/images/shampoo.jpeg', number: '02', note: 'Sulfate free · Paraben free', text: 'A gentle, moisturising shampoo formulated with aloe vera to cleanse the hair and scalp while helping restore moisture. Leaves hair feeling clean, soft and refreshed.', ingredients: 'Cocobetaine, decyl glucoside, aloe vera juice, aqua, glycerin, polyquaternium-7, preservative and fragrance.', how: 'Apply to wet hair and massage the scalp and hair into a lather. Rinse thoroughly. Repeat if desired.' },
  { name: 'Deep Conditioner', price: '₦5,000', type: 'Intense moisture & repair', image: '/images/deep-conditioner.jpeg', number: '03', note: 'Honey · Shea butter · Pro-vitamin B5', text: 'A rich, nourishing conditioner formulated to deeply moisturise, soften and strengthen the hair. Helps improve manageability, reduce dryness and leave hair feeling soft and smooth.', ingredients: 'Aqua, glycerin, honey, shea butter, BTMS, cetyl alcohol, panthenol (pro-vitamin B5), polyquaternium-7, vitamin E, nourishing oil blends, fragrance and preservative.', how: 'After shampooing, apply generously to clean, damp hair, focusing on mid-lengths and ends. Detangle gently. Leave for 30–40 minutes, then rinse thoroughly. Cover with a shower cap for deeper conditioning.' },
  { name: 'Leave-in Conditioner', price: '₦5,500', type: 'Hibiscus & flaxseed', image: '/images/leave-in-conditioner.jpeg', number: '04', note: 'Moisturise · Soften · Detangle', text: 'A lightweight leave-in conditioner formulated with hibiscus and flaxseed to hydrate, detangle and soften. Helps hair feel smooth, manageable and cared for without the weight.', ingredients: 'Hibiscus, flaxseed, aqua, glycerin, panthenol (pro-vitamin B5), polyquaternium-7, cetyl alcohol, BTMS, hydrolyzed silk protein, vitamin E, nourishing oil blends, fragrance and preservative.', how: 'Apply to clean, damp hair, focusing on mid-lengths and ends. Do not rinse. Style as desired.' },
];

function Mark({ light = false }) { return <a className={`wordmark ${light ? 'wordmark-light' : ''}`} href="#home" aria-label="Bloomance home"><span className="mark-icon"><img className="brand-emblem" src="/images/bloomance-emblem.png" alt="" /></span><span className="mark-name">BLOOMANCE</span><span className="mark-tag">BLOOM WITH CONFIDENCE</span></a>; }

function App() {
  const [active, setActive] = useState(null);
  const [open, setOpen] = useState(false);
  const [menu, setMenu] = useState(false);
  return <>
    <div className="announcement"><span>Thoughtful care for every curl, coil & crown</span><a href={wa}>Let your hair bloom <ArrowRight size={13}/></a></div>
    <header className="header"><button className="mobile-toggle" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close menu' : 'Open menu'}>{menu ? <X/> : <Menu/>}</button><Mark/><nav className={menu ? 'nav nav-open' : 'nav'}><a href="#story" onClick={() => setMenu(false)}>Our story</a><a href="#ritual" onClick={() => setMenu(false)}>The ritual</a><a href="#products" onClick={() => setMenu(false)}>Products</a><a href="#contact" onClick={() => setMenu(false)}>Contact</a></nav><a className="header-cta" href={wa}>Shop the collection <ArrowUpRight size={15}/></a></header>

    <main>
      <section className="hero" id="home"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-line"/>BOTANICAL HAIR CARE, MADE WITH CARE</span><h1>Let your hair<br/><em>bloom</em> beautifully.</h1><p>Rooted in botanical ingredients and thoughtful rituals, Bloomance is here to help you care for your hair with confidence—one wash day at a time.</p><div className="hero-actions"><a className="button button-primary" href="#products">Explore the collection <ArrowRight size={16}/></a><a className="text-link" href="#story">Meet Bloomance <ArrowDown size={15}/></a></div><div className="hero-note"><span className="note-flower">✿</span><span>CARE THAT STARTS<br/>AT THE ROOT</span><i/><span>MADE TO HELP<br/>HAIR FEEL ITS BEST</span></div></div><div className="hero-visual"><div className="hero-image-wrap"><img src="/images/product-editorial-1.jpeg" alt="Bloomance botanical hair-care collection"/><div className="image-label"><span>BOTANICAL RITUALS</span><b>Made for your<br/>everyday bloom.</b></div></div><div className="round-stamp"><span>ROOTED IN CARE</span><Leaf size={22}/><span>BLOOM IN CONFIDENCE</span></div><div className="hero-index">BLOOMANCE <span>—</span> 01 / 04</div></div></section>

      <section className="ticker" aria-label="Bloomance values"><div>ROOTED IN NATURE <b>✿</b> MADE WITH INTENTION <b>✿</b> CARE FOR EVERY CROWN <b>✿</b> BLOOM WITH CONFIDENCE <b>✿</b> ROOTED IN NATURE <b>✿</b></div></section>

      <section className="story section-pad" id="story"><div className="story-image"><img src="/images/product-editorial-2.jpeg" alt="Bloomance hair-care products styled in a warm, natural setting"/><span className="photo-caption">A LITTLE MORE LOVE FOR YOUR HAIR</span></div><div className="story-copy"><span className="eyebrow"><span className="eyebrow-line"/>THE BLOOMANCE WAY</span><h2>Good hair days<br/>begin with <em>good care.</em></h2><p>Bloomance is a hair-care brand built around the belief that caring for your hair can feel simple, considered and joyful.</p><p>Our collection brings together gentle cleansing, deep nourishment and botanical oils to support a routine that feels good from scalp to strand. No rush. Just consistent care, made for the way your hair blooms.</p><a className="text-link text-link-dark" href="#ritual">Discover our approach <ArrowRight size={16}/></a><div className="values"><div><Leaf/><span>BOTANICAL<br/>INSPIRATION</span></div><div><Heart/><span>THOUGHTFUL<br/>HAIR CARE</span></div><div><Sparkles/><span>YOUR ROUTINE,<br/>YOUR BLOOM</span></div></div></div></section>

      <section className="ritual section-pad" id="ritual"><div className="ritual-head"><div><span className="eyebrow"><span className="eyebrow-line"/>A ROUTINE TO RETURN TO</span><h2>Your wash day,<br/><em>made more mindful.</em></h2></div><p>Build a simple ritual around what your hair needs. Start fresh, give it nourishment, and finish with care that stays.</p></div><div className="ritual-steps"><article><span className="step-no">01</span><div className="step-icon"><Droplets/></div><span className="step-title">Cleanse</span><p>Massage shampoo into wet hair and scalp. Rinse well and repeat if desired.</p><span className="step-product">GENTLE ALOE VERA SHAMPOO</span></article><article><span className="step-no">02</span><div className="step-icon"><Heart/></div><span className="step-title">Condition</span><p>Apply deep conditioner to clean, damp hair. Give it 30–40 minutes, then rinse.</p><span className="step-product">DEEP CONDITIONER</span></article><article><span className="step-no">03</span><div className="step-icon"><Sparkles/></div><span className="step-title">Leave in</span><p>Work leave-in through damp hair, focusing on mid-lengths and ends. Do not rinse.</p><span className="step-product">LEAVE-IN CONDITIONER</span></article><article><span className="step-no">04</span><div className="step-icon"><Leaf/></div><span className="step-title">Nourish</span><p>Massage a little botanical oil into the scalp and smooth through ends as needed.</p><span className="step-product">BOTANICAL HAIR OIL</span></article></div></section>

      <section className="products section-pad" id="products"><div className="products-head"><div><span className="eyebrow"><span className="eyebrow-line"/>MEET YOUR NEW FAVOURITES</span><h2>Care for every<br/><em>step of the ritual.</em></h2></div><p>Four thoughtful essentials. One feel-good routine.<br/>Find the products that feel right for your hair.</p></div><div className="product-grid">{products.map((p) => <article className="product-card" key={p.number}><button className="product-image" onClick={() => setActive(p)} aria-label={`Learn more about ${p.name}`}><img src={p.image} alt={p.name}/><span className="product-count">{p.number} / 04</span><span className="product-view">VIEW DETAILS <ArrowUpRight size={14}/></span></button><div className="product-meta"><div><span className="product-type">{p.type}</span><h3>{p.name}</h3></div><button className="product-arrow" onClick={() => setActive(p)} aria-label={`View ${p.name}`}><ArrowUpRight size={18}/></button></div><p className="product-note">{p.note}</p><p className="product-price">{p.price}</p></article>)}</div></section>

      <section className="quote"><span className="quote-flower">✿</span><p>“Bloom with confidence.”</p><span>YOUR HAIR-CARE RITUAL, ROOTED IN CARE</span></section>

      <section className="contact section-pad" id="contact"><div className="contact-image"><img src="/images/product-editorial-1.jpeg" alt="The Bloomance hair-care collection"/><div className="contact-image-text">A ritual that<br/><em>feels like you.</em></div></div><div className="contact-copy"><span className="eyebrow"><span className="eyebrow-line"/>LET’S TALK HAIR</span><h2>Ready to find<br/>your <em>Bloomance?</em></h2><p>Questions about your routine or ready to place an order? We’d love to hear from you. Send us a message and let’s find your next favourite.</p><a className="button button-light" href={wa}>Chat with us on WhatsApp <ArrowUpRight size={16}/></a><div className="socials"><span>FIND YOUR BLOOM</span><a href={ig} aria-label="Bloomance on Instagram" target="_blank" rel="noreferrer"><Instagram/></a><a href={tt} aria-label="Bloomance on TikTok" target="_blank" rel="noreferrer"><span className="tiktok">♪</span></a></div></div></section>
    </main>

    <footer className="footer" id="contact"><Mark light/><span className="footer-motto">A LITTLE CARE GOES A LONG WAY.</span><span className="copyright">© {new Date().getFullYear()} BLOOMANCE. BLOOM WITH CONFIDENCE.</span><a href="#home" className="back-top">BACK TO TOP ↑</a></footer>

    {active && <div className="modal-backdrop" onClick={() => setActive(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setActive(null)} aria-label="Close details"><X/></button><div className="modal-image"><img src={active.image} alt=""/></div><div className="modal-copy"><span className="eyebrow">BLOOMANCE · {active.type.toUpperCase()}</span><h2 id="modal-title">{active.name}</h2><p className="modal-price">{active.price}</p><p>{active.text}</p><h4>INGREDIENTS</h4><p className="modal-small">{active.ingredients}</p><h4>HOW TO USE</h4><p className="modal-small">{active.how}</p><a className="button button-primary" href={wa}>Ask us about this product <ArrowUpRight size={16}/></a></div></section></div>}
  </>;
}

createRoot(document.getElementById('root')).render(<App/>);
